#159987403 social media authentication
andela/metis-ah pull request #13
Opened 2018-09-07 11:18 UTC by IyiKuyoro

#### What does this PR do?
Implement social media authentication
#### Description of Task to be completed?
- Install passport and passport strategies
- setup authentication with facebook
- setup authentication with google
#### How should this be manually tested?
1. Clone the repository.
2. Checkout the `ft-social-login-#159987403` branch.
3. Run npm install on your local machine.
4. Run the db migrations using `npm run migrate`.
5. Start the server using `npm run start_dev`.
5. Access the following routes on a browser; `localhost:8000/api/users/auth/google` and `localhost:8000/api/users/auth/facebook`.
#### Any background context you want to provide?
This feature should enable users to signup and signin using their social media accounts on google and facebook
#### What are the relevant pivotal tracker stories?
#159987403

2018-09-07 11:36 UTC, iAmao requested changes
Nice one again 👍

2018-09-07 11:36 UTC, iAmao commented on server/config/passportSetup.js
> +    callbackURL: 'http://localhost:8000/api/users/auth/google/redirect',
Add this to env variable

2018-09-08 11:51 UTC, IyiKuyoro commented
@iAmao resolved all issues and implemented a mock test that mocks the facebook and google authentication call

2018-09-11 13:11 UTC, IyiKuyoro commented
@iAmao  This PR is ready to merge

2018-09-12 12:04 UTC, iAmao commented on test/test.spec.js
> +          // console.log(res);
Remove commented code

2018-09-12 12:07 UTC, iAmao requested changes
Nice, just fix the minors

2018-09-12 12:07 UTC, iAmao commented on test/test.spec.js
> +          // console.log(res);
Remove commented code

2018-09-12 12:22 UTC, iAmao approved these changes

2018-09-12 12:22 UTC, merged