#159987402 implement password reset
andela/metis-ah pull request #15
Opened 2018-09-08 16:09 UTC by tomiadebanjo

#### What does this PR do?
Implement password reset

#### Description of Task to be completed?
- Install sendgridAPI
- create endpoints for users to request for a password reset.
- setup functionality to allow users reset their password.

#### How should this be manually tested?
1. Clone the repository.
2. Checkout the `ft-user-password-reset-159987402` branch.
3. Run npm install on your local machine.
4. Run the db migrations using `npm run migrate`.
5. Start the server using `npm run start_dev`.
5. You can test the following endpoints using postman
`localhost:8000/api/v1/users/api/auth/reset-password/` 
`localhost:8000/api/v1/users/api/auth/reset-password/:token`

#### What are the relevant pivotal tracker stories?
[ #159987402](https://www.pivotaltracker.com/story/show/159987402)

2018-09-10 11:48 UTC, iAmao requested changes
Nice, but always handle edge cases and errors, keep function as simple as possible.

2018-09-10 11:48 UTC, iAmao commented on server/controllers/userController.js
> +      .then((user) => {
No catch block for this. If something happens users will never get a response

2018-09-10 11:48 UTC, iAmao commented on server/controllers/userController.js
> +    }).then((user) => {
No catch block for this. If something happens users will never get a response

2018-09-10 11:48 UTC, iAmao commented on server/controllers/userController.js
> +      }).then(() => res.status(200).jsend.success({
No catch block for this. If something happens users will never get a response

2018-09-10 11:48 UTC, iAmao commented on server/helpers/generateToken.js
> +const generateToken = (time, ...args) => {
You could just use an object instead of a spread operator

2018-09-10 14:25 UTC, tomiadebanjo commented on server/controllers/userController.js
> +      .then((user) => {
Fixed

2018-09-10 14:25 UTC, tomiadebanjo commented on server/controllers/userController.js
> +    }).then((user) => {
Fixed

2018-09-10 14:25 UTC, tomiadebanjo commented on server/controllers/userController.js
> +      }).then(() => res.status(200).jsend.success({
I've added catch blocks for all the then's.

2018-09-13 21:28 UTC, iAmao approved these changes

2018-09-13 21:28 UTC, merged