#159987404 users should be able to create their profiles
andela/metis-ah pull request #19
Opened 2018-09-11 10:00 UTC by joeeasy

**What does this PR do?**
Implements a feature that allows users to: 
- view other users profile

- their profile

- upload a profile picture

- add a bio

**Description of Task to be completed?**
- install `Multer`
- install `Cloudinary`
- write tests for the endpoint
- write a validator middleware

**How should this be manually tested?**
Clone the repository.
Checkout the `ft-users-can-update-profile` branch.
Run `NPM START` on your local machine.
Run database migrations using `npm run migrate`.
Start the server using `NPM START`.

**You can test the following endpoints using postman**
PUT `localhost:8000/api/v1/users/update` to update a user's profile
GET `localhost:8000/api/v1/users/:userId` to view a user's profile
HEADERS
- authorization -> paste your token there
- Content-Type -> application/form-data

REQUIRED FIELDS
-    username: `string`
-   email: `string`

**What are the relevant pivotal tracker stories?**
#159987404

2018-09-12 11:20 UTC, iAmao requested changes

2018-09-12 11:20 UTC, iAmao commented on server/controllers/userController.js
> +      const file = !req.file ? '../../upload/dummy-profile.png' : dataUri(req);
I'm guessing, you are uploading a default image if the user did not pass an image. Instead, what we should do is have a default image URL in the column, and not make any call to cloudinary if the user did not upload a file.

2018-09-19 13:55 UTC, jojitoon approved these changes

2018-09-19 13:55 UTC, JojiAndela commented on swagger.json
> +
remove spaces

2018-09-20 11:45 UTC, iAmao requested changes
Nice 👍  but, there were some style violations you need to address. Also, some suggestions.

2018-09-20 11:45 UTC, iAmao commented on test/users.test.spec.js
> +  it("should return successfully when a user's profile is successfully updated", (done) => {
Prefer single quotes over double quotes as suggested by the style guide

2018-09-20 11:45 UTC, iAmao commented on test/users.test.spec.js
> +        interest: 'gaming, movies, music, tech',
in future we might want to have this as a table

2018-09-20 11:45 UTC, iAmao commented on test/users.test.spec.js
> +        expect(res.body.data.message).to.equal('Your profile has been updated successfully');
You are not asserting that any value actually changed here

2018-09-20 11:45 UTC, iAmao commented on test/users.test.spec.js
> +  it("should return successfully when a user's profile is successfully updated", (done) => {
Prefer single quotes over double quotes as suggested by the style guide

2018-09-20 11:45 UTC, iAmao commented on test/users.test.spec.js
> +        // interest: 'gaming, movies, music, tech',
avoid pushing commented code

2018-09-20 11:45 UTC, iAmao commented on test/users.test.spec.js
> +  it("should return successfully when a user's profile is successfully updated", (done) => {
Also, isn't this a duplicate test?

2018-09-20 11:45 UTC, iAmao commented on test/users.test.spec.js
> +        expect(res.body.data.message).to.equal('Your profile has been updated successfully');
There is actually no response validating that this works

2018-09-20 11:45 UTC, iAmao commented on test/users.test.spec.js
> +        assert.isObject(res.body, 'is an object containing the user details');
expect the user's details as well

2018-09-20 11:45 UTC, iAmao commented on test/users.test.spec.js
> +        expect(res).to.have.status(400);
Server should return 404 In this case

2018-09-20 11:45 UTC, iAmao commented on test/users.test.spec.js
> +  it('should not parseInt if Id has alphabet', (done) => {
This test is testing for the same case as above. We don't need it

2018-09-20 11:45 UTC, iAmao commented on server/controllers/userController.js
> +   * @param {Object} res The the response object
take out one of the `the`

2018-09-20 11:45 UTC, iAmao commented on server/controllers/userController.js
> +      const interest = (req.body.interest) ? req.body.interest.split(',') : null;
The braces are not needed here though

2018-09-20 11:45 UTC, iAmao commented on server/controllers/userController.js
> +      return res.status(400).jsend.error({
Lets just return 404 for this case

2018-09-21 11:05 UTC, iAmao approved these changes

2018-09-21 11:05 UTC, merged