#159987395 Setup test with mocha and chai
andela/metis-ah pull request #2
Opened 2018-08-27 16:34 UTC by DanielAdek

#### What does this PR do?
Setup unit test for with mocha, chai, and chai-http for the project.

#### Description of Task to be completed?

- install babel
-  install mocha
-  install chai
-  install chai-HTTP
-  initialize babel with `.babelrc`
-  create `app.js` for a simple app
-  create a simple test functionality

#### How should this be manually tested?

1. clone repository
2. checkout the ch-setup-test-159987395
3. run `npm install` to install packages
4. run `npm test` to run test

#### Any background context you want to provide?
This set up a simple test environment for a comprehensive app

#### What are the relevant pivotal tracker stories?
#159987395

2018-08-27 18:50 UTC, johngorithm commented
looks **good**

2018-08-27 18:53 UTC, johngorithm reviewed
looks good

2018-08-28 13:42 UTC, iAmao commented
@DanielAdek Please fix all these HoundCI comments

2018-08-28 15:21 UTC, IyiKuyoro approved these changes
Good and ready for merge.

2018-08-28 15:21 UTC, iAmao requested changes

2018-08-28 15:21 UTC, iAmao commented on test/test.spec.js
> +        })
@DanielAdek missing semi colon

2018-08-28 15:21 UTC, iAmao commented on test/test.spec.js
> +    })
@DanielAdek Missing semicolon.

2018-08-28 18:01 UTC, iAmao approved these changes

2018-08-28 18:02 UTC, merged