#159987411 User can tag an article and view articles
andela/metis-ah pull request #20
Opened 2018-09-11 21:26 UTC by JojiAndela

#### What does this PR do?
Implement functionality to allow user view tags and associated articles

#### Description of Task to be completed?

- modify database relationship
- implement the functionality to create tags from article creation
- implement the functionality to view all articles
- implement the functionality to view a tag with all associated articles

#### How should this be manually tested?

- Clone the repository.
- Checkout the `ft-article-tagging-159987411`  branch.
- Run npm install on your local machine.
- Run the db migrations using npm run migrate.
- Start the server using npm run start_dev.
- Using postman or any similar. get  a token upon registration and use it to test these routes:
  `localhost:8000/api/v1/tags`
`localhost:8000/api/v1/tags/:tagName`

#### Any background context you want to provide?
This feature will enable a user to view all tags and articles associated with the tags.

#### What are the relevant pivotal tracker stories?
#159987411

2018-09-17 21:14 UTC, iAmao requested changes
This is good nice job

2018-09-17 21:14 UTC, iAmao commented on server/app.js
> +
Unnecessary blank line

2018-09-17 21:14 UTC, iAmao commented on server/controllers/articleController.js
> +      const tags = !fields.tags || fields.tags === '' ? []
When working with ternary operators try modeling it like this:
```
condition
 ? action
 : action
```

2018-09-17 21:14 UTC, iAmao commented on server/controllers/tagController.js
> +
Unnecessary blank lines

2018-09-17 21:14 UTC, iAmao commented on server/controllers/tagController.js
> +
Unnecessary blank lines

2018-09-17 21:14 UTC, iAmao commented on server/migrations/20180911162010-create-tagging.js
> +
Unnecessary blank lines

2018-09-17 21:14 UTC, iAmao commented on server/models/tagging.js
> +  const Taggings = sequelize.define('Taggings', {
Follow naming convention of pivot Table here

2018-09-18 11:41 UTC, iAmao submitted a review, later dismissed

2018-09-18 11:41 UTC, iAmao commented on server/models/articlesTags.js
> +  const Taggings = sequelize.define('ArticlesTags', {
this is still called `Tagging`

2018-09-18 12:02 UTC, tomiadebanjo approved these changes

2018-09-19 11:45 UTC, merged