#159987417 Users should be able to bookmark articles for reading later
andela/metis-ah pull request #23
Opened 2018-09-13 10:01 UTC by joeeasy

**What does this PR do?**
Implements a feature that allows users to: 
- bookmark an article
- view all their bookmarked articles

**Description of Task to be completed?**
- write the test for bookmarking articles
- write the test for getting all bookmarked articles
- write documentation for bookmarking an article
**How should this be manually tested?**
Clone the repository.
Check out the `ft-users-can-bookmark-article` branch.
Run `NPM INSTALL` on your local machine.
Run database migrations using `npm run migrate`.
Start the server using `NPM RUN START_DEV`.

**You can test the following endpoints using postman**
POST `localhost:8000/api/v1/articles/bookmarks` to bookmark an article
GET `localhost:8000/api/v1/articles/bookmarks` to view all bookmarked articles
HEADERS
- authorization -> paste your token there

REQUIRED FIELDS
POST
-    title: `string`
-   id(article ID): `number`

**What are the relevant pivotal tracker stories?**
#159987417

2018-09-13 11:32 UTC, IyiKuyoro commented on server/controllers/articleController.js
> +      return res.status(500).jsend.fail({
This is not a server error

2018-09-13 11:55 UTC, joeeasy commented on server/controllers/articleController.js
> +      return res.status(500).jsend.fail({
Thanks, man!
I've quickly fixed it

2018-09-19 14:06 UTC, jojitoon requested changes

2018-09-19 14:06 UTC, JojiAndela commented on server/controllers/articleController.js
> +      .spread((bookmark, created) => (!(created) ? res.status(400).jsend.fail({ message: 'You have already bookmarked this article' })
good. but for easy readability put the ternary operator in this format: 
```
condition to check
? value if the condition is satisfied
: value if the condition is not satisfied
```

2018-10-18 11:59 UTC, iAmao requested changes

2018-10-18 11:59 UTC, iAmao commented on server/controllers/articleController.js
> +          message: 'Your book mark has been created successfully'
`bookmark` not `book mark`

2018-10-18 11:59 UTC, iAmao commented on server/controllers/articleController.js
> +          message: 'Here are your bookmarks',
We do not need a message here

2018-10-18 12:07 UTC, merged