#159987397 APIs documentation using swagger
andela/metis-ah pull request #7
Opened 2018-08-30 17:15 UTC by DanielAdek

#### What does this PR do?
Setup APIs documentation using swagger
#### Description of Task to be completed?
* Install swagger-ui-express
* Install cors
* create a swagger.json file in the root directory of your project
* on your browser open editor.swagger.io
* click on convert and save as Json button, in file navigation bar of the site above
* after it has downloaded, copy the code in the file, into the swagger.json file in your project
* edit the code according to your project.
#### How should this be manually tested?
1. Clone repository
2. On your terminal run this command git checkout ft-swagger-docs-159987397
3. run npm install to install packages
4. run npm start
5. open your browser and enter `localhost:8000/api-docs`
#### Any background context you want to provide?
This setup is a documentation of all the APIs endpoint you documented in the swagger.json file
#### What are the relevant pivotal tracker stories?
#159987397

2018-08-31 17:10 UTC, jojitoon approved these changes
good work. swagger docs running.

2018-09-03 11:34 UTC, iAmao requested changes

2018-09-03 11:34 UTC, iAmao commented on swagger.json
> +          "read:pets": "read your pets"
Remove this config

2018-09-03 11:34 UTC, iAmao commented on swagger.json
> +            "sims"
remove sims tag

2018-09-03 11:34 UTC, iAmao commented on swagger.json
> +      "description": "Auto's Heven [https://metis-ah-staging.herokuapp.com/](https://metis-ah-staging.herokuapp.com/) is a platform that allows you to share your knowledge across the world",
Fix typo "Auto's Heven" should be Author's Haven

2018-09-03 11:34 UTC, iAmao commented on .eslintrc.json
> +    "import/no-unresolved": [2, { "commonjs": true}],
Fix blank space before } to follow airbnb style guides

2018-09-03 16:06 UTC, iAmao approved these changes

2018-09-03 16:06 UTC, merged