#159987391 Configure Authors Haven to use PostgreSQL as DB Engine
andela/metis-ah pull request #8
Opened 2018-08-31 08:33 UTC by jamesenejo

#### What does this PR do?
Integrates PostgreSQL and Sequelize

#### Description of Task to be completed?
- Modify folder structure
- Install pg and pg-hstore
- Install sequelize and sequelize-cli
- Add Sequelize configuration file
- Modify model index file to ES6
- Create database connection
- Modify generated model to ES6
- Modify config file to use es6

#### What are the relevant pivotal tracker stories?
#159987391

2018-08-31 17:08 UTC, IyiKuyoro approved these changes

2018-09-03 16:07 UTC, iAmao requested changes

2018-09-03 16:07 UTC, iAmao commented on .sequelizerc
> +    "config": path.resolve('./server/config', 'config.json'),
Use the `config.js` file

2018-09-04 10:52 UTC, iAmao approved these changes

2018-09-04 10:52 UTC, merged